# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dreamhunter Blog
subtitle: 你指尖跃动的电光，是我此生不变的信仰
description:
keywords:
author: dreamhunter
language: zh-CN
# timezone:

# sidebar-avatar: imgs/avatar.jpg

# avatar_style:
#   radius: true

url: https://jcstaff.club
root: /
# permalink: :year/:month/:day/:title/
permalink: :year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:


# Category & Tag
default_category:
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 12
pagination_dir: page

theme: casper

search:
  path: search.json
  field: post

# github_username:    jinmu333

# 文章样式(是否首行缩进)：
# post_style:
#   indent: 0

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-koharu
  display:
    position: left
    width: 200
    height: 400
  mobile:
    show: false

# 友情链接
# friends: [
#     {
#         title: "Github",
#         href: "https://github.com"
#     },{
#         title: "Baidu",
#         href: "https://baidu.com"
#     },{
#         title: "Google",
#         href: "https://google.com"
#     }
# ]